language: node_js

node_js:
    - '12'

script:
    - yarn build

deploy:
    provider: netlify
    site: $SITE_ID
    auth: $AUTH_TOKEN
    dir: out
    prod: true
    edge: true
    on:
        branch: master
