language: node_js

node_js:
  - '8'

addons:
  ssh_known_hosts: zackad.com

script:
  - yarn build

before_deploy:
  - openssl aes-256-cbc -K $encrypted_e651d210d85a_key -iv $encrypted_e651d210d85a_iv
    -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist/ $DEPLOY_TARGET_PATH
  on:
    branch: master
