name: Build and Deploy to Netlify

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build_and_deploy:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            - uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-
            - name: Setup NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
            - name: Install dependencies
              run: yarn install
            - name: Build artifact
              env:
                  NODE_OPTIONS: --openssl-legacy-provider # Workaround for nodejs 18 compatibility
              run: yarn build
            - name: Deploy to Netlify
              uses: nwtgck/actions-netlify@v1.1
              with:
                  publish-dir: out
                  production-branch: master
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  deploy-message: 'Deploy from GitHub Actions'
                  enable-pull-request-comment: true
                  enable-commit-comment: false
                  overwrites-pull-request-comment: true
              env:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
              timeout-minutes: 1
